<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SmartParkingWebAPI\**" />
    <Compile Remove="SmartParkingSytem.Tests\**" />
    <Compile Remove="smart_parking_system\**" />
    <Content Remove="SmartParkingWebAPI\**" />
    <Content Remove="SmartParkingSytem.Tests\**" />
    <Content Remove="smart_parking_system\**" />
    <EmbeddedResource Remove="SmartParkingWebAPI\**" />
    <EmbeddedResource Remove="SmartParkingSytem.Tests\**" />
    <EmbeddedResource Remove="smart_parking_system\**" />
    <None Remove="SmartParkingWebAPI\**" />
    <None Remove="SmartParkingSytem.Tests\**" />
    <None Remove="smart_parking_system\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
